name: Node.js CI

on:
  push:
    branches: [ "main" ] # push가 되면 job을 실행해라
  pull_request:
    branches: [ "main" ] # pr이 발생하면 job을 실행해라 

# 실행될 내용 
jobs:
  build:

    runs-on: ubuntu-latest # 우분투 운영체제에서 실행해라, Runnder의 종류를 지정해주는 것 \
    # 가장 최신의 우분투 버전 
    
    steps:
    # 4개의 스텝으로 이루어져있음 > build라는 job에. job은 하나 존재함 
    
    - uses: actions/checkout@v4 # 액션을 지정 > 마켓플레이스를 활용할 수 있음 (actions 밑에 checkout 사용) - repository에서 소스코드 가져옴 
    - name: Use Node.js 18.x # 이름을 줌 
      uses: actions/setup-node@v4 # setup-node를 실행해라 - node.js 환경을 설정함 -> 우리가 올려놓은 소스코드를 꺼내온 후 node.js 환경 세팅한 후 명령어 실행 
      with: # node.js를 실행하는데 필요한 정보를 제공함 
        node-version: 18.x
        cache: 'npm'
    - run: npm ci # 필요한 내용 설치
    - run: npm test # npm test 도 실행
